name: firebase_auth
description: Flutter plugin for Firebase Auth, enabling Android and iOS
  authentication using passwords, phone numbers and identity providers
  like Google, Facebook and Twitter.
homepage: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_auth/firebase_auth
version: 0.18.0+1

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.firebase.auth
        pluginClass: FlutterFirebaseAuthPlugin
      ios:
        pluginClass: FLTFirebaseAuthPlugin
      macos:
        pluginClass: FLTFirebaseAuthPlugin
      web:
        default_package: firebase_auth_web

dependencies:
  meta: ^1.0.4
  firebase_core: ">=0.5.0 <0.6.0"
  firebase_auth_platform_interface:
    path: ../firebase_auth_platform_interface
  firebase_auth_web:
    path: ../firebase_auth_web

  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.8.0
  async: ^2.3.0
  mockito: ^4.1.1
  test: ^1.3.0
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^1.0.2

environment:
  sdk: ">=2.0.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.4 <2.0.0"
